replicaCount: 2

image:
  repository: "ghcr.io/javierg90/kubescope"
  tag: "4e0a45c"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-credentials

app:
  environment: staging
  version: "4e0a45c"
  message: KubeScope - Staging
  featureExperimental: false

ingress:
  enabled: true
  host: stg.kubescope.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
