replicaCount: 3

image:
  repository: "ghcr.io/javiergm-usabana/kubescope"
  tag: "4e0a45c"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-credentials

app:
  environment: production
  version: "4e0a45c"
  message: KubeScope - Production
  featureExperimental: false

ingress:
  enabled: true
  host: kubescope.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
