replicaCount: 1

image:
  repository: ghcr.io/javiergm-usabana/kubescope
  tag: "d3d52e2"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-credentials

app:
  environment: dev
  version: "d3d52e2"
  message: KubeScope - Development
  featureExperimental: true

ingress:
  enabled: true
  host: dev.kubescope.local

resources:
  requests:
    cpu: 25m
    memory: 48Mi
  limits:
    cpu: 150m
    memory: 128Mi

autoscaling:
  enabled: false
